trainer:
  callbacks:
    - class_path: src.utils.utils.HmsPredictionWriter
      init_args:
        output_filepath: /workspace/hms/labels/pseudolabel/submission_2.csv
data:
  init_args:
    test_is_train: true
    split_index: 2
ckpt_path: /workspace/hms/models/best_2.ckpt