trainer:
  callbacks:
    - class_path: src.utils.utils.HmsPredictionWriter
      init_args:
        output_filepath: /workspace/hms/labels/pseudolabel/submission_3.csv
        drop_eeg_sub_id: false
data:
  init_args:
    test_is_train: true
ckpt_path: /workspace/hms/models/best_3.ckpt