trainer:
  callbacks:
    - class_path: src.utils.utils.HmsPredictionWriter
      init_args:
        output_filepath: /workspace/hms/labels/pseudolabel/submission_1.csv
data:
  init_args:
    test_is_train: true
ckpt_path: /workspace/hms/models/best_1.ckpt