seed_everything: 28490463
trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: hms
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
      init_args:
        logging_interval: step
    - class_path: src.utils.utils.ModelCheckpointNoSave
      init_args:
        save_top_k: 1
        monitor: val_loss_kld
        every_n_epochs: 1
        mode: min
        save_on_train_epoch_end: false
        save_last: true

  # limit_train_batches: 10
  # limit_val_batches: 10
  max_epochs: 16
  num_sanity_val_steps: 0
  accumulate_grad_batches: 1
  reload_dataloaders_every_n_epochs: 0
  log_every_n_steps: 1
  gradient_clip_val: null
  check_val_every_n_epoch: 1
  precision: bf16-mixed

  gradient_clip_algorithm: norm
  deterministic: true
  benchmark: false
  enable_checkpointing: true

  fast_dev_run: false
  profiler: null
  detect_anomaly: false
  
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  enable_progress_bar: null
  enable_model_summary: null
  inference_mode: true
  use_distributed_sampler: true
  barebones: false
  plugins: null
  sync_batchnorm: false
  default_root_dir: null
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
model:
  class_path: src.model.modules.HmsModule
  init_args:
    model: hms_classifier
    model_kwargs:
      embed_dim: 128
      num_heads: 4
      dropout: 0.1
      depth: 2
      cheap_cross: false
      pool: cls
      use: all
    weight_by_n_voters: false
    optimizer_init: 
      class_path: torch.optim.AdamW
      init_args:
        lr: 3e-4
    lr_scheduler_init:
      class_path: src.utils.lr_scheduler.PiecewiceFactorsLRScheduler
      init_args:
        milestones: [0, 0.1, 1.0]
        pieces:
          - class_path: src.utils.lr_scheduler.LinearLRSchedulerPiece
            init_args:
              start_lr: 1e-1
              stop_lr: 1
          - class_path: src.utils.lr_scheduler.CosineLRSchedulerPiece
            init_args:
              start_lr: 1
              stop_lr: 1e-2
    pl_lrs_cfg:
      interval: step
      frequency: 1
    finetuning: null
    lr_layer_decay: 1.0
    log_norm_verbose: false
    n_bootstrap: 0
    skip_nan: false
data:
  class_path: src.data.datamodule.HmsDatamodule
  init_args:
    dataset_dirpath: '/workspace/data_external/'
    split_index: 0
    n_splits: 5
    random_subrecord_mode: discrete
    load_kwargs:
      gaussianize_mode: null
      do_mel_eeg: false
      do_clip_eeg: true
    eeg_norm_strategy: meanstd
    spectrogram_norm_strategy: log
    label_smoothing_n_voters: null
    cache_dir: /workspace/data_external/.cache
    batch_size: 32
    num_workers: 8
    pin_memory: false
    prefetch_factor: 2
    persistent_workers: false
