trainer:
  accumulate_grad_batches: 4
model:
  class_path: src.model.modules.HmsModule
  init_args:
    model: maxvit_rmlp_base_rw_384.sw_in12k_ft_in1k
    model_kwargs: 
      pretrained: true
      in_chans: 1
      img_size: 640
data:
  class_path: src.data.datamodule.HmsDatamodule
  init_args:
    cache_dir: /workspace/data_external/.cache_img
    batch_size: 6