trainer:
  deterministic: false
  accumulate_grad_batches: 6
model:
  class_path: src.model.modules.HmsModule
  init_args:
    model: hf_hub:timm/eva02_base_patch14_448.mim_in22k_ft_in22k_in1k
    model_kwargs: 
      pretrained: true
      in_chans: 1
      dynamic_img_size: true
      dynamic_img_pad: true
    lr: 0.00003
data:
  class_path: src.data.datamodule.HmsDatamodule
  init_args:
    cache_dir: /workspace/data_external/.cache_img
    batch_size: 4