model:
  class_path: src.model.modules.HmsModule
  init_args:
    model: maxvit_tiny_tf_512.in1k
    model_kwargs: 
      pretrained: true
      in_chans: 1
      img_size: 640
data:
  class_path: src.data.datamodule.HmsDatamodule
  init_args:
    cache_dir: /workspace/data_external/.cache_img
    batch_size: 16